### ISSUE TITLE
index outside of array

### ISSUE THREAD

**Issue by Denominator13** [FelipeVieiraVendramini/AutoUpdater#4]
`System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AutoUpdater.FrmMain.ConnectToAutoUpdateServer()
   at AutoUpdater.FrmMain.FrmMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

Not sure what I'm missing?

**Comment by Denominator13** [comment]
Nevermind I was building it with framework 4.8 lol, just had to check the internet on how to install netframework 4.5 to VS2022, installed it and now no errors :)
