### ISSUE TITLE
index outside the bounds of an array

### ISSUE THREAD

**Issue by Denominator13** [FelipeVieiraVendramini/AutoUpdater#5]
`System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AutoUpdater.FrmMain.ConnectToAutoUpdateServer()
   at AutoUpdater.FrmMain.FrmMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by Denominator13** [comment]
Okay I think I figured it out I can't use my http to get the autopatch.txt I can only use a https which I unfortunately do not have lol

**Comment by Denominator13** [comment]
I now have https and face the index outside the bounds of an array again?

**Comment by Denominator13** [comment]
Okay seems I was missing a / at the end of patch.txt

**Comment by FelipeVieiraVendramini** [comment]
I'll take a look later to see if I can submit a fix to avoid it. Sorry for the late reply, I haven't been using Github anymore. I migrated to Gitlab.

**Comment by Denominator13** [comment]
No need to apologise :) Tbh I prefer the older version because it closes but I can't seem to figure out how to make it accept https? I will keep at it until I figure it out but for now it's time to sleep lol, and I'm on Gitlab also :D
